# Generated by Django 6.0.6 on 2026-06-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('villa', 'Villa'), ('land', 'Land'), ('office', 'Office'), ('shop', 'Shop')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('mortgage', 'Mortgage'), ('mortgage_rent', 'Mortgage & Rent')], max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('area', models.PositiveIntegerField(help_text='Square meters')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('storage_room', models.BooleanField(default=False)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('mortgage_price', models.BigIntegerField(blank=True, null=True)),
                ('rent_price', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Properties.property')),
            ],
        ),
    ]
